services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: speech_therapy
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d   
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d speech_therapy"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: speech_therapy
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "4173:4173"
